# Generated by Django 3.2.7 on 2021-12-06 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211205_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_friends',
            field=models.ManyToManyField(blank=True, related_name='_mainapp_user_requested_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
