# Generated by Django 3.2.7 on 2021-12-09 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requested_friends',
        ),
        migrations.AddField(
            model_name='user',
            name='requests_from',
            field=models.ManyToManyField(blank=True, related_name='_mainapp_user_requests_from_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
